neos-modding-group/neos-mod-manifest

.github/workflows/markdown-gen.yml, README-template.md, README.md, gen_readme.py
Using Github actions we can generate a modlist directly into the README file, making the manifest the one and only source of truth, de-duplicating the current work of having two different mod list documents.
=> Generate modlist to README from mod manifest

manifest.json
I added hash generation to my own mods release script so I did very minor cleanup on all my mods so that there's released versions of all of them with the hashes included https://git.ljoonal.xyz/ljoonal/Neos-Mods/releases/tag/v2022-04-12
=> Add newest version of mod releases

gen_readme.py
Since the time is not localized, it's currently potentially confusing for people who're used to seeing times that are localized to their timezones with JS.
An alternative to this approach would be to make JS that does localize the time, but as some users might not have JS enabled, I think that just specifying that it's UTC time is good enough.
=> Specify timezone explicitly in the last updated at text

.github/workflows/markdown-gen.yml, gen_readme.py
- Makes the pages markdown generation tool more flexibly so it can be easier tested locally with standard std-in/out pipes (instead of only relying on seeing the CI fail _after_ a PR has been merged due to it requiring very specific file paths to read to/from).
- Comments the code more.
- Cleans up the code that excludes some entries from being shown, hopefully avoiding edge cases that would've been possible with the current filtering where the code could generate a category title but no entries in the category.
- Preemptively adds an exclude for a category called "NSFW" from being generated to the markdown, and filters pre-release versions too.
- Parses version numbers and sorts the versions
- Adds the version numbers/links to the mods, and the changelog
- Changes the header levels back …
=> Improve markdown generation

manifest.json
The description was outdated, and the versions listed were very out of date and did not include the fixes for Linux Native
=> Make my mod's listing better

manifest.json
- added version 3.1.0.0, which adds configurable keybind for the desktop tab control panel
- added version 3.2.0.0, which adds ability to disable the mod trough mod config (requires Neos restart to take effect)
=> Added versions 3.1.0.0 and 3.2.0.0 of 3DDashOnScreen

manifest.json
Deprecate my version of NoEscape in favor of [Banane9's fork](https://github.com/Banane9/NeosNoEscape).
=> Deprecate zkxs/NoEscape

manifest.json
url should be the full url path for downloading an artifact
=> Fix YouWantDarkmode url

manifest.json
Several mods were listed with incorrect versions when referring to what the tag/release was called.
=> Multiple minor version corrections

manifest.json
- added version 3.3.0.0 of 3DDashOnScreen, which adds removal of the grab lock, that forces last grabbed item to stay grabbed if dash is opened in screen mode
=> Added version 3.3.0.0 of 3DDashOnScreen

manifest.json
- added version 3.4.0.0 of 3DDashOnScreen - compatibility hotfix for compatibility with ExitAndDiscardHomesKeybind
- added version 1.0.0.0 of ExitAndDiscardHomesKeybind - allows to exit without saving changes in home world using Ctrl+Alt+F4 key shortcut; can be disabled trough mod config
=> Added v3.4.0.0 of 3DDashOnScreen and v1.0.0.0 of ExitAndDiscardHomesKeybind

.github/workflows/markdown-gen.yml
[Documentation](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)
This is useful if mod-list-template.md is changed over in the website repo, and we don't want to manually copy the changes over to the generated mods.md file.
=> Allow manually triggering a mod list generation

.github/pull_request_template.md
I believe the end-of-file merge conflicts are caused by having to alter the comma of the preceding mod, so I'm recommending people add their mods literally anywhere *except* the end of the file.
=> Note on reducing merge conflicts

gen_notif.py
Apparently explicitly copying something does not, in fact, properly copy it.
=> Fix bad embed gen

manifest.json
Both versions of UserJoinLeaveNotifications were under different categories. Now they are both under "Dash Tweaks"
The repo owner of the fork is now first in the author list for their fork.
=> Changed fork of UserJoinLeaveNotifications to be under "Dash Tweaks", Changed author order on fork

.github/pull_request_template.md
Clarify `deprecated` flag usage for old mods, not necessary on older versions of a mod in most cases.
=> Clarify `deprecated` flag usage

gen_notif.py
From my testing I found that stuff like `\n` will get escaped to `\\n` which means descriptions instead of containing new lines, will contain literal `\n`.
This also reverts the completely broken and stupid code that was supposed to do this job.
=> Fix broken notifications workflow.

manifest.json
Repo no longer exists or was made private
Also updated sourceLocation to point to the correct repo in case it returns
=> Deprecate NeosWCFaceIntegration

manifest.json
See https://github.com/Earthmark/Neos-TypeType
=> Added net.earthmark.GenericTypeType to the manifest

gen_notif.py
It's come to my attention that it's not in the workflow of some subset of Discord users to use this radio button:
Therefore, I'm now of the opinion that while it feels painfully redundant, announcement ping roles are a necessity for some users to be made aware that an announcement has occurred. I've already created the `@mod release ping` aka `<@&1079268851952406571>` role in the Discord, so all that's left is to update the webhook to actually ping it.
Relevant Discord API documentation:
- [Execute Webhook](https://discord.com/developers/docs/resources/webhook#execute-webhook)
- [Allowed Mentions Object](https://discord.com/developers/docs/resources/channel#allowed-mentions-object)
- [Message Formatting](https://discord.com/developers/docs/reference#message-formatting)
=> Ping `@mod release ping` on mod releases

schema.json
This allows for mods that are intended to *never* be valid for a given platform, for example a mod that has Linux-only fixes.
Relevant conversation: https://github.com/neos-modding-group/neos-mod-manifest/pull/217#discussion_r1086172549
=> Allow an entire mod to be flagged as broken for a platform

.github/workflows/atom-feed-update.yml
This is why the Github Action to regenerate the Atom feed is failing.
It wasn't checking out enough of the git history to compare the older mod manifest with the new one.
=> Fix Atom feeder unable to find old mod manifest

atom_feeder.py
The atom feeder should now
a) not crash anymore and
b) also append a mod's release URL to the feed items.
=> Fix Atom Feeder

manifest.json
See https://github.com/Earthmark/Neos-TypeType/releases/tag/0.1.2 for release notes.
=> Updated GenericTypeType to 0.1.2

manifest.json
skipping adding v1.4.0.0 to the manifest so this version also includes the changes from that version: added a button to show a record metadata editor
=> Eia485 add 1.4.1.0 get item link

schema.json
This change extends the platform compatibility flags to include android.
Useful for purposes mentioned in #235, where mods may require Android/Quest-specific features.
=> Add manifest flag for android platforms

manifest.json, schema.json
the `General UI Tweaks` category could be removed completely if reviews deemed necessary by moving NeosBetterIMESupport into Bug Workarounds and by moving ReduceAnimation and SquishPanels into Visual Tweaks
maybe a `notifications` category should be created, by my count there are 5 entries that would go under that.
=> recagorized some entries
