neos-modding-group/neos-mod-manifest

- LICENSE.txt
Verbatim copy/paste from https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt
> Add CC0 license

- manifest.json
I reviewed the latest version of everything with the `TODO_REVIEW` tag removed with a decompiler. I did not try if the functionality works in game, but confirming that the mods aren't spoopy is enough IMO since these already trusted mods/authors, and I'm sure that someone else can attest to them working in game. :)
Also added the latest version of inspectrum since it was missing.
> Review a bunch of mods

- manifest.json
Adds the latest NML version. I did do a short review on the NML binary if that matters, though I feel like NML probably doesn't need to be reviewed, as if zkxs starts being sussy this repository won't have much of a point anyways ~
> Update NML version & links

- docs/auditing-process.md
- docs/categories.md
- docs/mod-guidelines.md
- docs/submission-tutorial.md
This adds some initial mod submission and review guidelines. Let me know if I've written something foolish or omitted anything.
> Add submission guidelines

- docs/submission-tutorial.md
Change the JSON lang to JSON5 which github
> Fix JSON comments lang

- manifest.json
Added latest 2 releases of 3D Dash On Screen with their associated SHA256 checksums and links.
> Added versions 2.0.0 and 2.1.0 of 3D Dash On Screen

- .github/workflows/markdown-gen.yml
- README.md
> Fix links to the new website

- manifest.json
Added new version of 3DDashOnScreen and its associated SHA256 checksum.
> Added version 3.0.0.0 of 3DDashOnScreen

- gen_readme.py
Fixes #22 
Fixes https://github.com/neos-modding-group/neos-modding-group.github.io/issues/5
> Add last updated text to the mods page

- manifest.json
> fix version number for MaybeJump

- gen_readme.py
- manifest.json
I am exceptionally rusty at python, so please make sure I'm not doing anything stupid @ljoonal
> Mods with exclusively vulnerable versions are not added to the list

- .github/workflows/markdown-gen.yml
- gen_readme.py
So I finally bothered to open it in my IDE then.
Changed to not needlessly checkout this repo to a master folder so that testing the python markdown gen locally is easier.
And also just made the whole not outputting mods thing more modular with the ~ magic of functions ~
> Fix pages generation

- manifest.json
the square image thing is now behind a config option in the main mod
> my fork of gifimporter is not needed anymore

- manifest.json
> Add latest latest log

- .github/workflows/markdown-gen.yml
Since gh actions broke due to using an old version I assume.
> Use newer version of python

- .github/workflows/markdown-gen.yml
> Python3.10 -> python3

- .github/workflows/markdown-gen.yml
But switching away from it now is too late so let's just try to get it to work....
> Python was a mistake for pages gen

- .github/workflows/markdown-gen.yml
- requirements.txt
> Deal with github actions autorinning pip

- manifest.json
It doesn't make too much sense to have whole categories with just a single mod in them.
> Merge two developers categories

- manifest.json
LJ will be happy to see I've nuked my `enabled` config, which was doing basically nothing of value
> CloudHomeAccessLevel 1.1.0

- .gitignore
- README.md
- review.sh
Fixes #20 
Note that the script currently does not try to smartly resolve any non-linux-standard paths, as I wasn't sure anyone on windows would have the required linux commands to run the script to begin with.
If it's the case, a few if conditions can easily be added to check standard paths, and people with really non-standard paths can always just edit the path at the top.
> Feature review script

- manifest.json
I almost put an easter egg in this mod  
but then I didn't.
> Add VoiceQuality

- manifest.json
> Add DesktopToolShortcutRemapper 2

- manifest.json
Allows you to receive notifications while your status is set to Busy.
> NotificationsWhenBusy

- manifest.json
> Add a bunch of new mods from me

- manifest.json
> Add Interfacial Absence

- manifest.json
Hopefully I did everything right :)
> Add NeosDisableGamepads to manifest

- manifest.json
is this a change we should make?
> move harmony to nml_libs

- manifest.json
And a newer version of one mod
> Added more mods

- manifest.json
> Add three new mods

- manifest.json
Added all of my missing mods and updated ones already listed
Also added Gareth's particle workshop mod
Was putting this off for a while and finally got the motivation to do this 
Was unsure of how to handle the Discord.Net dlls for [HeadlessTweaks](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks) so I put them in the artifacts array of the releases
> Added all of my mods and Gareth48's

- manifest.json
Apparently the join/leave notifications mod wasn't even in the manifest before... it is now.
> Add User Join/Leave, Session Capacity and Go To Bed

- manifest.json
:^
yall wana do this again lol
> use 4 spaces

- manifest.json
While this is amusing, it must go:
> Shrink HeadlessTweaks' huge bullet point down to normal size

- manifest.json
> Adding Webservers mod to manifest.json

- .editorconfig
- .github/workflows/lint.yml
- manifest.json
It turns out the EC check workflow requires a `run` step, which is new to me.
This won't automatically re-run for existing PRs, but if you press the "Update Branch" button the new commit on the PR will trigger the tests to run.
> Actually run the editorconfig check

- .editorconfig
- .github/pull_request_template.md
- README.md
- docs/review-script.md
Working on #135
- Simplify the readme
- Link to new docs on the website
- Create a PR template
- Allow trailing whitespace in markdown, because it's actually meaningful
> Documentation update

- .github/workflows/lint.yml
- .github/workflows/markdown-gen.yml
Forks should not be running the website publish.
Forks should be running the linting.
> Handle workflows correctly on forks

- .github/workflows/release-notifications.yml
- .gitignore
- gen_notif.py
- gen_readme.py
- util.py
This adds another reason for the manifest's existence. In the future this could also potentially download the file(s), check the hashes, and then attach the file(s) to the discord message.
> Add automated new mod version notifications

- .github/workflows/release-notifications.yml
- If condition should hopefully be correct now
- Remove an extra space from discord POST payload, not that it breaks anything but not like it has any purpose either
> Fix a few minor GHA notification issues

- gen_notif.py
- schema.json
- Removes extra space from behind the mod version in the embed title
- Fixes releaseUrl capitalization issue that led to embeds not having urls
- Updates schema to allow for more customization for the embed (or any other implementations too)
> Hopefully the last minor notification fixes

- manifest.json
> Adding my mods to the manifest

- manifest.json
Since schema wasn't bumped in #158 which added more allowed fields
> Bumps the schema version

- gen_notif.py
> convert color’s hex to an int as per discord’s requirements

- manifest.json
Added the following three my mods.
- ReleaseSRanipalOnQuit
- SaveItemTweaks
- NeosBetterIMESupport
> Add my mods

- manifest.json
> fix GifImporter

- manifest.json
- Added ComponentAttacher v1.0.1
- Also fixed version 1.0.0 missing a filename property
> Added ComponentAttacher v1.0.1

- manifest.json
> Add new release and deprecate old ones

- manifest.json
Add initial version of EnumDropdown
> Add EnumDropdown

- manifest.json
> Add LocalStorage 1.1.0

- manifest.json
Added:
* New Version of EditorTabbing
* Add hantabaru1014 as Author to EditorTabbing for PR
* New Version of UserJoinLeaveNotifications
* New Mod CorrectGizmoScaling
* New Mod BoundedUIX
* New Mod ComponentAttacherSearch
Also added myself as an Author on Art's color drop mod for the PR 🤔
> More mods and updates!

- manifest.json
Add the required information for the AnimJ Import Fix mod (JworkzAnimJImportFixMod).
> docs: add JworkzAnimJImportFixMod v1.0.0 info

- manifest.json
- added Screen Dash Fixer mod, which applies just the misc. tweaks from 3D Dash On Screen
> Added Screen Dash Fixer

- manifest.json
> add GifImporter 1.1.3

- manifest.json
Updated my domain name, updating mod ids to match
> Update Mod ids to be `net.` instead of `tk.`

- manifest.json
> Deprecate GifImporter

- manifest.json
Added my custom logix browser to the manifest
> Add CustomLogixBrowser to the manifest

- manifest.json
Adds updated versions for:
* ComponentAttacherFavorites
* ComponentAttacherRecents
* ComponentAttacherSearch
In one pull request, as they depend on updates to the search mod.
> Add ComponentAttacher* Updates

- manifest.json
> Add TNMTMISTYFANLTTSSYCREANKNOWSBIYHWYP v1.1.0

- manifest.json
> add OpenLinkedVariableSpace v1.0.1

- .github/workflows/lint.yml
Probably enough to check task 1 on #255
> Update actions/checkout v1 and v2

- manifest.json
> Add SessionUrlJoin

- manifest.json
> Update CustomLogixBrowser to v1.1.0

- manifest.json
This is my trial run for registering a mod in the mod manifest.
This mod spawns a window with some LogiX whenever you import many images/videos in a short timeframe.
That window allows you to reparent all or only parts of the imports.
> added mpmxyz/NeosMassImportPacker

- manifest.json
> Add NeosTextureSettings v1.0.0

- manifest.json
> Added UnsafeLogix

- manifest.json
> Add QuickFolderOpener

- manifest.json
also added a conflict to one of my mods
> add JustBoudnedUix

- manifest.json
> Add ImportDefaultsChange v1.0.0 and VRLogixRotateFix v1.0.1

- manifest.json
> Change several audio mods from Misc to Audio

- manifest.json
for what it's worth: only one method call got changed in SlotAddingPatches.SceneInspectorPatches.OnAddChildPostfix()
> Add BoundedUIX 2.4.1 patch and SessionTabOverhaul 1.1.0 update

- manifest.json
add info for mod that fixes missing contact request notification
> docs: add mod info regarding notfication fix

- manifest.json
Added mod JworksNeosFixFrickenSync info into the manifest.
EDITED: Removed checklist. Don't know why PR was saved with that, or I might've been too tired when posting...
> docs: add JworksNeosFixFrickenSync mod info
